// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Artist → Links*
 */
export interface ArtistDocumentDataLinksItem {
  /**
   * Type field in *Artist → Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.links[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<
    "Soundcloud" | "Bandcamp" | "Instagram" | "Resident Advisor" | "Other"
  >;

  /**
   * Link field in *Artist → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type ArtistDocumentDataSlicesSlice = never;

/**
 * Content for Artist documents
 */
interface ArtistDocumentData {
  /**
   * Name field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.name
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Artist*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Artist*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.image
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Artist*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.video
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Links field in *Artist*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.links[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<ArtistDocumentDataLinksItem>>;

  /**
   * Slice Zone field in *Artist*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.slices[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArtistDocumentDataSlicesSlice> /**
   * Meta Title field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: artist.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: artist.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Artist*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Artist document from Prismic
 *
 * - **API ID**: `artist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtistDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ArtistDocumentData>, "artist", Lang>;

type ContentPageDocumentDataSlicesSlice =
  | ProductListSlice
  | TextColumnSlice
  | TextImageBlockSlice
  | EmbedBlockSlice
  | NewsletterSubscriptionSlice
  | ContentSectionSlice;

/**
 * Content for Content page documents
 */
interface ContentPageDocumentData {
  /**
   * Title field in *Content page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Render frame field in *Content page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_page.render_frame
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;

  /**
   * Slice Zone field in *Content page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContentPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Content page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: content_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Content page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: content_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Content page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Content page document from Prismic
 *
 * - **API ID**: `content_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentPageDocumentData>,
    "content_page",
    Lang
  >;

type EventDocumentDataSlicesSlice = never;

/**
 * Item in *Event → Artists*
 */
export interface EventDocumentDataArtistsItem {
  /**
   * Artist field in *Event → Artists*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[].artist
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  artist: ContentRelationshipFieldWithData<
    [
      {
        id: "artist";
        fields: [
          "name",
          "description",
          "image",
          { id: "links"; fields: ["type", "link"] },
          "video",
        ];
      },
    ]
  >;

  /**
   * Start time field in *Event → Artists*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: When does the artist start
   * - **API ID Path**: event.artists[].start_time
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  start_time: prismic.TimestampField;

  /**
   * Duration (minutes) field in *Event → Artists*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Duration in minutes 60 = 1 hour, 120 = 2 hours,...
   * - **API ID Path**: event.artists[].duration
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  duration: prismic.NumberField;

  /**
   * Stage field in *Event → Artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (Optional) name of the stage where artist will be. Leave blank if only 1 stage per venue
   * - **API ID Path**: event.artists[].stage
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stage: prismic.KeyTextField;

  /**
   * Image override field in *Event → Artists*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[].image_override
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_override: prismic.ImageField<never>;

  /**
   * Video override field in *Event → Artists*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[].video_override
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_override: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Description override field in *Event → Artists*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[].description_override
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description_override: prismic.RichTextField;
}

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Cover image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.cover_image
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Promo image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.promo_image
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  promo_image: prismic.ImageField<never>;

  /**
   * Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.title
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Video field in *Event*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Video for the event
   * - **API ID Path**: event.video
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice> /**
   * Venue field in *Event*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: event.venue
   * - **Tab**: Venue
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */;
  venue: prismic.ContentRelationshipField<"venue"> /**
   * Start field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: When does the event start
   * - **API ID Path**: event.date_start
   * - **Tab**: Schedule
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */;
  date_start: prismic.TimestampField;

  /**
   * End field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: When does the event end
   * - **API ID Path**: event.date_end
   * - **Tab**: Schedule
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  date_end: prismic.TimestampField;

  /**
   * Artists field in *Event*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[]
   * - **Tab**: Schedule
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  artists: prismic.GroupField<Simplify<EventDocumentDataArtistsItem>> /**
   * Event type field in *Event*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: event.event_type
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/select
   */;
  event_type: prismic.SelectField<
    "Single day" | "Festival" | "Guest appearance"
  >;

  /**
   * Visibility field in *Event*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: event.visibility
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visibility: prismic.SelectField<"Visible" | "Hidden">;

  /**
   * Colour field in *Event*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Event colour
   * - **API ID Path**: event.colour
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  colour: prismic.ColorField /**
   * Meta Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: event.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: event.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Item in *Podcast → Tracklist*
 */
export interface PodcastDocumentDataTracklistItem {
  /**
   * Title field in *Podcast → Tracklist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Artist field in *Podcast → Tracklist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[].artist
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  artist: prismic.KeyTextField;

  /**
   * Embed field in *Podcast → Tracklist*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[].embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  embed: prismic.EmbedField;

  /**
   * Link field in *Podcast → Tracklist*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type PodcastDocumentDataSlicesSlice = never;

/**
 * Content for Podcast documents
 */
interface PodcastDocumentData {
  /**
   * Cover image field in *Podcast*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Episode name field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.episode_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  episode_name: prismic.KeyTextField;

  /**
   * Description field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Artist field in *Podcast*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.artist
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  artist: ContentRelationshipFieldWithData<
    [
      {
        id: "artist";
        fields: [
          "name",
          "description",
          "image",
          "video",
          { id: "links"; fields: ["type", "link"] },
        ];
      },
    ]
  >;

  /**
   * Embed link field in *Podcast*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.embed_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  embed_link: prismic.EmbedField;

  /**
   * Tracklist field in *Podcast*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tracklist: prismic.GroupField<Simplify<PodcastDocumentDataTracklistItem>>;

  /**
   * Slice Zone field in *Podcast*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PodcastDocumentDataSlicesSlice> /**
   * Meta Title field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: podcast.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: podcast.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Podcast*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Podcast document from Prismic
 *
 * - **API ID**: `podcast`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PodcastDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PodcastDocumentData>,
    "podcast",
    Lang
  >;

/**
 * Item in *Product → Images*
 */
export interface ProductDocumentDataImagesItem {
  /**
   * image field in *Product → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Product → Related products*
 */
export interface ProductDocumentDataRelatedProductsItem {
  /**
   * Related product field in *Product → Related products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.related_products[].related_product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  related_product: ContentRelationshipFieldWithData<
    [
      {
        id: "product";
        fields: [
          "title",
          { id: "images"; fields: ["image"] },
          "price",
          "product_category",
          "product_type",
          "sorting_weight",
          "product_status",
          "description",
          "product_visibility",
        ];
      },
    ]
  >;

  /**
   * Call to action field in *Product → Related products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Example, "Goes great with", "To wear with your shirt"
   * - **API ID Path**: product.related_products[].call_to_action
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  call_to_action: prismic.KeyTextField;
}

type ProductDocumentDataSlicesSlice = never;

type ProductDocumentDataSlices1Slice = never;

/**
 * Item in *Product → Variants*
 */
export interface ProductDocumentDataVariantsItem {
  /**
   * Variant value field in *Product → Variants*
   *
   * - **Field Type**: Select
   * - **Placeholder**: What is the variants value
   * - **API ID Path**: product.variants[].variant_value
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant_value: prismic.SelectField<
    "XS" | "S" | "M" | "L" | "XL" | "XXL" | "Black" | "White"
  >;

  /**
   * Variant type field in *Product → Variants*
   *
   * - **Field Type**: Select
   * - **Placeholder**: What type of a variant is it
   * - **Default Value**: Size
   * - **API ID Path**: product.variants[].variant_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant_type: prismic.SelectField<"Size" | "Colour", "filled">;
}

/**
 * Item in *Product → Regional eligibility *
 */
export interface ProductDocumentDataRegionalEligibilityItem {
  /**
   * Region field in *Product → Regional eligibility *
   *
   * - **Field Type**: Select
   * - **Placeholder**: Region of availability, choose none if available everywhere
   * - **API ID Path**: product.regional_eligibility[].region
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  region: prismic.SelectField<
    | "Slovenia"
    | "EU"
    | "Non-EU Europe"
    | "UK"
    | "North America"
    | "Australia"
    | "Japan"
  >;
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of the product
   * - **API ID Path**: product.title
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Product category field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Which category best describes the product
   * - **Default Value**: Merch
   * - **API ID Path**: product.product_category
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  product_category: prismic.SelectField<
    | "Merch"
    | "Music"
    | "Albums"
    | "Donations"
    | "Tickets"
    | "Licenses"
    | "Currencies"
    | "Other",
    "filled"
  >;

  /**
   * Product type field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Is this a physical or digital item
   * - **Default Value**: Physical
   * - **API ID Path**: product.product_type
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  product_type: prismic.SelectField<"Physical" | "Digital", "filled">;

  /**
   * Images field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.images[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<ProductDocumentDataImagesItem>>;

  /**
   * Video field in *Product*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Video for product
   * - **API ID Path**: product.video
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descriptive text to highlight the features of the product
   * - **API ID Path**: product.description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Related products field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.related_products[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  related_products: prismic.GroupField<
    Simplify<ProductDocumentDataRelatedProductsItem>
  >;

  /**
   * Special notice field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional - Special notice or disclaimer goes here
   * - **API ID Path**: product.special_notice
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  special_notice: prismic.KeyTextField;

  /**
   * Checkout description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Item description visible in Stripe
   * - **API ID Path**: product.checkout_description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  checkout_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Product status field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: What is the current product status
   * - **Default Value**: Available
   * - **API ID Path**: product.product_status
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/select
   */;
  product_status: prismic.SelectField<
    "Available" | "Preorder" | "Coming soon" | "Out of stock" | "Sold out",
    "filled"
  >;

  /**
   * Product visibility field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Is the product visible on site?
   * - **Default Value**: Visible
   * - **API ID Path**: product.product_visibility
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  product_visibility: prismic.SelectField<"Visible" | "Hidden", "filled">;

  /**
   * Price (EUR) field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Price of the product in EUR
   * - **API ID Path**: product.price
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Weight (g) field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Weight of the product in grams
   * - **API ID Path**: product.weight
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  weight: prismic.NumberField;

  /**
   * Featured product field in *Product*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product.featured_product
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured_product: prismic.BooleanField;

  /**
   * Sorting weight field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: The higher the number the higher on the list of products
   * - **API ID Path**: product.sorting_weight
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  sorting_weight: prismic.NumberField;

  /**
   * Related to event field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.related_to_event
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  related_to_event: ContentRelationshipFieldWithData<
    [
      {
        id: "event";
        fields: [
          "title",
          "venue_name",
          "date_start",
          "venue_address",
          "venue_logo",
        ];
      },
    ]
  >;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices1[]
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices1: prismic.SliceZone<ProductDocumentDataSlices1Slice> /**
   * Variants field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.variants[]
   * - **Tab**: Variants
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  variants: prismic.GroupField<Simplify<ProductDocumentDataVariantsItem>> /**
   * Regional eligibility  field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.regional_eligibility[]
   * - **Tab**: Limitations
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  regional_eligibility: prismic.GroupField<
    Simplify<ProductDocumentDataRegionalEligibilityItem>
  >;

  /**
   * Quantity limit field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Leave empty if no limit
   * - **API ID Path**: product.quantity_limit
   * - **Tab**: Limitations
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  quantity_limit: prismic.NumberField;

  /**
   * Cutoff date field in *Product*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: When does the product stop being eligible for sale, clear if sales always permitted
   * - **API ID Path**: product.cutoff_date
   * - **Tab**: Limitations
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  cutoff_date: prismic.TimestampField /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

type VenueDocumentDataSlicesSlice = never;

/**
 * Content for Venue documents
 */
interface VenueDocumentData {
  /**
   * Name field in *Venue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.name
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Venue*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Address field in *Venue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Full address, with street, zip, city
   * - **API ID Path**: venue.address
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Venue logo field in *Venue*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.venue_logo
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  venue_logo: prismic.ImageField<never>;

  /**
   * Map location url field in *Venue*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.map_location_url
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  map_location_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Venue*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.slices[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<VenueDocumentDataSlicesSlice> /**
   * Meta Title field in *Venue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: venue.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Venue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: venue.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Venue*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Venue document from Prismic
 *
 * - **API ID**: `venue`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VenueDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<VenueDocumentData>, "venue", Lang>;

export type AllDocumentTypes =
  | ArtistDocument
  | ContentPageDocument
  | EventDocument
  | PodcastDocument
  | ProductDocument
  | VenueDocument;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface ContentSectionSliceDefaultPrimary {
  /**
   * Content field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type ContentSectionSliceVariation = ContentSectionSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `content_section`
 * - **Description**: ContentSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSectionSlice = prismic.SharedSlice<
  "content_section",
  ContentSectionSliceVariation
>;

/**
 * Primary content in *EmbedBlock → Default → Primary*
 */
export interface EmbedBlockSliceDefaultPrimary {
  /**
   * Media field in *EmbedBlock → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: embed_block.default.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  media: prismic.EmbedField;

  /**
   * Heading field in *EmbedBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embed_block.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *EmbedBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embed_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for EmbedBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EmbedBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmbedBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EmbedBlock*
 */
type EmbedBlockSliceVariation = EmbedBlockSliceDefault;

/**
 * EmbedBlock Shared Slice
 *
 * - **API ID**: `embed_block`
 * - **Description**: EmbedBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EmbedBlockSlice = prismic.SharedSlice<
  "embed_block",
  EmbedBlockSliceVariation
>;

/**
 * Primary content in *GridTile → Default → Primary*
 */
export interface GridTileSliceDefaultPrimary {
  /**
   * Image field in *GridTile → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_tile.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Headline field in *GridTile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_tile.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Content field in *GridTile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_tile.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for GridTile Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridTileSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridTileSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GridTile*
 */
type GridTileSliceVariation = GridTileSliceDefault;

/**
 * GridTile Shared Slice
 *
 * - **API ID**: `grid_tile`
 * - **Description**: GridTile
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridTileSlice = prismic.SharedSlice<
  "grid_tile",
  GridTileSliceVariation
>;

/**
 * Primary content in *Newsletter → Default → Primary*
 */
export interface NewsletterSubscriptionSliceDefaultPrimary {
  /**
   * List type field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: General
   * - **API ID Path**: newsletter_subscription.default.primary.list_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  list_type: prismic.SelectField<"General" | "Festival", "filled">;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSubscriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSubscriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSubscriptionSliceVariation = NewsletterSubscriptionSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter_subscription`
 * - **Description**: NewsletterSubscription
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSubscriptionSlice = prismic.SharedSlice<
  "newsletter_subscription",
  NewsletterSubscriptionSliceVariation
>;

/**
 * Item in *ProductList → Manual selection → Primary → Products*
 */
export interface ProductListSliceManualPrimaryProductsItem {
  /**
   * Product field in *ProductList → Manual selection → Primary → Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.manual.primary.products[].product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product: ContentRelationshipFieldWithData<
    [{ id: "product"; fields: ["title"] }]
  >;
}

/**
 * Primary content in *ProductList → Category → Primary*
 */
export interface ProductListSliceDefaultPrimary {
  /**
   * Title field in *ProductList → Category → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title of the section
   * - **API ID Path**: product_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Category field in *ProductList → Category → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.default.primary.category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "Merch"
    | "Music"
    | "Albums"
    | "Donations"
    | "Tickets"
    | "Licenses"
    | "Currencies"
    | "Other"
  >;

  /**
   * Description field in *ProductList → Category → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of the section
   * - **API ID Path**: product_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Render frame field in *ProductList → Category → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_list.default.primary.render_frame
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;
}

/**
 * Category variation for ProductList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductListSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProductList → Featured → Primary*
 */
export interface ProductListSliceFeaturedPrimary {
  /**
   * Title field in *ProductList → Featured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.featured.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProductList → Featured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.featured.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Render frame field in *ProductList → Featured → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_list.featured.primary.render_frame
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;
}

/**
 * Featured variation for ProductList Slice
 *
 * - **API ID**: `featured`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductListSliceFeatured = prismic.SharedSliceVariation<
  "featured",
  Simplify<ProductListSliceFeaturedPrimary>,
  never
>;

/**
 * Primary content in *ProductList → Manual selection → Primary*
 */
export interface ProductListSliceManualPrimary {
  /**
   * Title field in *ProductList → Manual selection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.manual.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProductList → Manual selection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.manual.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Products field in *ProductList → Manual selection → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.manual.primary.products[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  products: prismic.GroupField<
    Simplify<ProductListSliceManualPrimaryProductsItem>
  >;

  /**
   * Render frame field in *ProductList → Manual selection → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_list.manual.primary.render_frame
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;
}

/**
 * Manual selection variation for ProductList Slice
 *
 * - **API ID**: `manual`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductListSliceManual = prismic.SharedSliceVariation<
  "manual",
  Simplify<ProductListSliceManualPrimary>,
  never
>;

/**
 * Slice variation for *ProductList*
 */
type ProductListSliceVariation =
  | ProductListSliceDefault
  | ProductListSliceFeatured
  | ProductListSliceManual;

/**
 * ProductList Shared Slice
 *
 * - **API ID**: `product_list`
 * - **Description**: ProductList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductListSlice = prismic.SharedSlice<
  "product_list",
  ProductListSliceVariation
>;

/**
 * Item in *TextColumns → Column - Text → Primary → Columns*
 */
export interface TextColumnSliceDefaultPrimaryColumnsItem {
  /**
   * Heading field in *TextColumns → Column - Text → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.columns[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *TextColumns → Column - Text → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.columns[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Item in *TextColumns → Column - With Image → Primary → Columns*
 */
export interface TextColumnSliceColumnWithImagePrimaryColumnsItem {
  /**
   * Image field in *TextColumns → Column - With Image → Primary → Columns*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.columns[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *TextColumns → Column - With Image → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.columns[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *TextColumns → Column - With Image → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.columns[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *TextColumns → Column - Text → Primary*
 */
export interface TextColumnSliceDefaultPrimary {
  /**
   * Heading field in *TextColumns → Column - Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *TextColumns → Column - Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Columns field in *TextColumns → Column - Text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  columns: prismic.GroupField<
    Simplify<TextColumnSliceDefaultPrimaryColumnsItem>
  >;
}

/**
 * Column - Text variation for TextColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextColumnSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextColumns → Column - With Image → Primary*
 */
export interface TextColumnSliceColumnWithImagePrimary {
  /**
   * Heading field in *TextColumns → Column - With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *TextColumns → Column - With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Columns field in *TextColumns → Column - With Image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  columns: prismic.GroupField<
    Simplify<TextColumnSliceColumnWithImagePrimaryColumnsItem>
  >;
}

/**
 * Column - With Image variation for TextColumns Slice
 *
 * - **API ID**: `columnWithImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnSliceColumnWithImage = prismic.SharedSliceVariation<
  "columnWithImage",
  Simplify<TextColumnSliceColumnWithImagePrimary>,
  never
>;

/**
 * Slice variation for *TextColumns*
 */
type TextColumnSliceVariation =
  | TextColumnSliceDefault
  | TextColumnSliceColumnWithImage;

/**
 * TextColumns Shared Slice
 *
 * - **API ID**: `text_column`
 * - **Description**: TextColumn
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnSlice = prismic.SharedSlice<
  "text_column",
  TextColumnSliceVariation
>;

/**
 * Item in *TextImageBlock → Left Align → Primary → Button*
 */
export interface TextImageBlockSliceDefaultPrimaryButtonItem {
  /**
   * Label field in *TextImageBlock → Left Align → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.default.primary.button[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *TextImageBlock → Left Align → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.default.primary.button[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Size field in *TextImageBlock → Left Align → Primary → Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: base
   * - **API ID Path**: text_image_block.default.primary.button[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"base" | "large" | "xlarge", "filled">;

  /**
   * Variant field in *TextImageBlock → Left Align → Primary → Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: text_image_block.default.primary.button[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"primary" | "secondary" | "tertiary", "filled">;
}

/**
 * Item in *TextImageBlock → Right Align → Primary → Button*
 */
export interface TextImageBlockSliceRightAlignPrimaryButtonItem {
  /**
   * Label field in *TextImageBlock → Right Align → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.rightAlign.primary.button[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *TextImageBlock → Right Align → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.rightAlign.primary.button[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Size field in *TextImageBlock → Right Align → Primary → Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: base
   * - **API ID Path**: text_image_block.rightAlign.primary.button[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"base" | "large" | "xlarge", "filled">;

  /**
   * Variant field in *TextImageBlock → Right Align → Primary → Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: text_image_block.rightAlign.primary.button[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"primary" | "secondary" | "tertiary", "filled">;
}

/**
 * Primary content in *TextImageBlock → Left Align → Primary*
 */
export interface TextImageBlockSliceDefaultPrimary {
  /**
   * Title field in *TextImageBlock → Left Align → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.default.primary.maintitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  maintitle: prismic.RichTextField;

  /**
   * Content field in *TextImageBlock → Left Align → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Image field in *TextImageBlock → Left Align → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button field in *TextImageBlock → Left Align → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.default.primary.button[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  button: prismic.GroupField<
    Simplify<TextImageBlockSliceDefaultPrimaryButtonItem>
  >;
}

/**
 * Left Align variation for TextImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextImageBlock → Right Align → Primary*
 */
export interface TextImageBlockSliceRightAlignPrimary {
  /**
   * Title field in *TextImageBlock → Right Align → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.rightAlign.primary.maintitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  maintitle: prismic.RichTextField;

  /**
   * Content field in *TextImageBlock → Right Align → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.rightAlign.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Image field in *TextImageBlock → Right Align → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.rightAlign.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button field in *TextImageBlock → Right Align → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.rightAlign.primary.button[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  button: prismic.GroupField<
    Simplify<TextImageBlockSliceRightAlignPrimaryButtonItem>
  >;

  /**
   * Addon field in *TextImageBlock → Right Align → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_block.rightAlign.primary.addon
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  addon: prismic.ContentRelationshipField<"sticker">;
}

/**
 * Right Align variation for TextImageBlock Slice
 *
 * - **API ID**: `rightAlign`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextImageBlockSliceRightAlign = prismic.SharedSliceVariation<
  "rightAlign",
  Simplify<TextImageBlockSliceRightAlignPrimary>,
  never
>;

/**
 * Slice variation for *TextImageBlock*
 */
type TextImageBlockSliceVariation =
  | TextImageBlockSliceDefault
  | TextImageBlockSliceRightAlign;

/**
 * TextImageBlock Shared Slice
 *
 * - **API ID**: `text_image_block`
 * - **Description**: TextImageBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextImageBlockSlice = prismic.SharedSlice<
  "text_image_block",
  TextImageBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArtistDocument,
      ArtistDocumentData,
      ArtistDocumentDataLinksItem,
      ArtistDocumentDataSlicesSlice,
      ContentPageDocument,
      ContentPageDocumentData,
      ContentPageDocumentDataSlicesSlice,
      EventDocument,
      EventDocumentData,
      EventDocumentDataSlicesSlice,
      EventDocumentDataArtistsItem,
      PodcastDocument,
      PodcastDocumentData,
      PodcastDocumentDataTracklistItem,
      PodcastDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataImagesItem,
      ProductDocumentDataRelatedProductsItem,
      ProductDocumentDataSlicesSlice,
      ProductDocumentDataSlices1Slice,
      ProductDocumentDataVariantsItem,
      ProductDocumentDataRegionalEligibilityItem,
      VenueDocument,
      VenueDocumentData,
      VenueDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentSectionSlice,
      ContentSectionSliceDefaultPrimary,
      ContentSectionSliceVariation,
      ContentSectionSliceDefault,
      EmbedBlockSlice,
      EmbedBlockSliceDefaultPrimary,
      EmbedBlockSliceVariation,
      EmbedBlockSliceDefault,
      GridTileSlice,
      GridTileSliceDefaultPrimary,
      GridTileSliceVariation,
      GridTileSliceDefault,
      NewsletterSubscriptionSlice,
      NewsletterSubscriptionSliceDefaultPrimary,
      NewsletterSubscriptionSliceVariation,
      NewsletterSubscriptionSliceDefault,
      ProductListSlice,
      ProductListSliceDefaultPrimary,
      ProductListSliceFeaturedPrimary,
      ProductListSliceManualPrimaryProductsItem,
      ProductListSliceManualPrimary,
      ProductListSliceVariation,
      ProductListSliceDefault,
      ProductListSliceFeatured,
      ProductListSliceManual,
      TextColumnSlice,
      TextColumnSliceDefaultPrimaryColumnsItem,
      TextColumnSliceDefaultPrimary,
      TextColumnSliceColumnWithImagePrimaryColumnsItem,
      TextColumnSliceColumnWithImagePrimary,
      TextColumnSliceVariation,
      TextColumnSliceDefault,
      TextColumnSliceColumnWithImage,
      TextImageBlockSlice,
      TextImageBlockSliceDefaultPrimaryButtonItem,
      TextImageBlockSliceDefaultPrimary,
      TextImageBlockSliceRightAlignPrimaryButtonItem,
      TextImageBlockSliceRightAlignPrimary,
      TextImageBlockSliceVariation,
      TextImageBlockSliceDefault,
      TextImageBlockSliceRightAlign,
    };
  }
}
