// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Artist → Links*
 */
export interface ArtistDocumentDataLinksItem {
  /**
   * Type field in *Artist → Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.links[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<
    "Soundcloud" | "Bandcamp" | "Instagram" | "Resident Advisor" | "Other"
  >;

  /**
   * Link field in *Artist → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type ArtistDocumentDataSlicesSlice = never;

/**
 * Content for Artist documents
 */
interface ArtistDocumentData {
  /**
   * Name * field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (Required) Name of the artist
   * - **API ID Path**: artist.name
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Artist*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Artist*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.image
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Artist*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.video
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Links field in *Artist*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.links[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<ArtistDocumentDataLinksItem>>;

  /**
   * Slice Zone field in *Artist*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.slices[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArtistDocumentDataSlicesSlice> /**
   * Show in artist page field in *Artist*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: artist.show_in_artist_page
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */;
  show_in_artist_page: prismic.BooleanField;

  /**
   * Is part of endemit crew field in *Artist*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: artist.is_endemit_crew
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_endemit_crew: prismic.BooleanField /**
   * Meta Title field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: artist.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: artist.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Artist*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Artist document from Prismic
 *
 * - **API ID**: `artist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtistDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ArtistDocumentData>, "artist", Lang>;

type ContentPageDocumentDataSlicesSlice =
  | SoundCloudSlice
  | PoemSlice
  | VinylPromoSectionSlice
  | EventListSlice
  | SpacerSlice
  | ArtistListSlice
  | TabsSlice
  | GridTileSlice
  | AccordionSlice
  | ImageGallerySlice
  | HeroSlice
  | PodcastListSlice
  | ProductListSlice
  | TextColumnSlice
  | EmbedBlockSlice
  | NewsletterSubscriptionSlice
  | ContentSectionSlice;

/**
 * Content for Content page documents
 */
interface ContentPageDocumentData {
  /**
   * Title field in *Content page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Render frame field in *Content page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_page.render_frame
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;

  /**
   * Slice Zone field in *Content page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContentPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Content page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: content_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Content page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: content_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Content page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Update frequency field in *Content page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.update_frequency
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  update_frequency: prismic.SelectField<
    "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never"
  >;

  /**
   * Priority field in *Content page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1.0-0.8: High priority : 0.7-0.4: Mid priority : 0.3-0.0: Low priority
   * - **API ID Path**: content_page.priority
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  priority: prismic.NumberField;
}

/**
 * Content page document from Prismic
 *
 * - **API ID**: `content_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentPageDocumentData>,
    "content_page",
    Lang
  >;

/**
 * Item in *Event → Artists*
 */
export interface EventDocumentDataArtistsItem {
  /**
   * Artist field in *Event → Artists*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[].artist
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  artist: ContentRelationshipFieldWithData<
    [
      {
        id: "artist";
        fields: [
          "name",
          "description",
          "image",
          { id: "links"; fields: ["type", "link"] },
          "video",
        ];
      },
    ]
  >;

  /**
   * Start time field in *Event → Artists*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: When does the artist start
   * - **API ID Path**: event.artists[].start_time
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  start_time: prismic.TimestampField;

  /**
   * Duration (minutes) field in *Event → Artists*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Duration in minutes 60 = 1 hour, 120 = 2 hours,...
   * - **API ID Path**: event.artists[].duration
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  duration: prismic.NumberField;

  /**
   * Stage field in *Event → Artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (Optional) name of the stage where artist will be. Leave blank if only 1 stage per venue
   * - **API ID Path**: event.artists[].stage
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stage: prismic.KeyTextField;

  /**
   * Image override field in *Event → Artists*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[].image_override
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_override: prismic.ImageField<never>;

  /**
   * Video override field in *Event → Artists*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[].video_override
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_override: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Description override field in *Event → Artists*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[].description_override
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description_override: prismic.RichTextField;
}

type EventDocumentDataSlicesSlice =
  | ArtistListSlice
  | EventListSlice
  | VinylPromoSectionSlice
  | PoemSlice
  | EmbedBlockSlice
  | PodcastListSlice
  | TextColumnSlice
  | TabsSlice
  | ProductListSlice
  | SpacerSlice
  | HeroSlice
  | GridTileSlice
  | ImageGallerySlice
  | NewsletterSubscriptionSlice
  | ContentSectionSlice
  | AccordionSlice;

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.title
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Cover image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.cover_image
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Promo image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.promo_image
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  promo_image: prismic.ImageField<never>;

  /**
   * Video field in *Event*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Video for the event
   * - **API ID Path**: event.video
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Art author field in *Event*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: event.art_author
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  art_author: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Venue field in *Event*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: event.venue
   * - **Tab**: Venue
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */;
  venue: ContentRelationshipFieldWithData<
    [
      {
        id: "venue";
        fields: [
          "name",
          "address",
          "venue_logo",
          "map_location_url",
          "coordinates",
          "description",
        ];
      },
    ]
  > /**
   * Start field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: When does the event start
   * - **API ID Path**: event.date_start
   * - **Tab**: Schedule
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */;
  date_start: prismic.TimestampField;

  /**
   * End field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: When does the event end
   * - **API ID Path**: event.date_end
   * - **Tab**: Schedule
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  date_end: prismic.TimestampField;

  /**
   * Artists field in *Event*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: event.artists[]
   * - **Tab**: Schedule
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  artists: prismic.GroupField<Simplify<EventDocumentDataArtistsItem>> /**
   * Event type field in *Event*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: event.event_type
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/select
   */;
  event_type: prismic.SelectField<
    "Single day" | "Festival" | "Guest appearance"
  >;

  /**
   * Colour field in *Event*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Event colour
   * - **API ID Path**: event.colour
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  colour: prismic.ColorField;

  /**
   * Visible in events field in *Event*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: event.visibility
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visibility: prismic.SelectField<"Visible" | "Hidden">;

  /**
   * Enable link to full page field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: event.enable_link_to_full_page
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  enable_link_to_full_page: prismic.BooleanField;

  /**
   * Annotation field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (Optional)
   * - **API ID Path**: event.annotation
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  annotation: prismic.KeyTextField;

  /**
   * Allow ticket scanning field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.allow_ticket_scanning
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  allow_ticket_scanning: prismic.BooleanField /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Rich content
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice> /**
   * Meta Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: event.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: event.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Content for Footer content documents
 */
interface FooterContentDocumentData {
  /**
   * Footer text field in *Footer content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_content.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_text: prismic.KeyTextField;

  /**
   * Links field in *Footer content*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Links in the footer
   * - **API ID Path**: footer_content.links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Link divider symbol field in *Footer content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_content.link_divider_symbol
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_divider_symbol: prismic.KeyTextField;
}

/**
 * Footer content document from Prismic
 *
 * - **API ID**: `footer_content`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterContentDocumentData>,
    "footer_content",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | TabsSlice
  | TextColumnSlice
  | PodcastListSlice
  | ProductListSlice
  | AccordionSlice
  | HeroSlice
  | ImageGallerySlice
  | NewsletterSubscriptionSlice
  | ContentSectionSlice
  | GridTileSlice
  | EmbedBlockSlice;

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type InnerContentDocumentDataSlicesSlice =
  | SpacerSlice
  | TextColumnSlice
  | ProductListSlice
  | PodcastListSlice
  | HeroSlice
  | GridTileSlice
  | ImageGallerySlice
  | NewsletterSubscriptionSlice
  | ContentSectionSlice
  | AccordionSlice
  | EmbedBlockSlice;

/**
 * Content for Inner content documents
 */
interface InnerContentDocumentData {
  /**
   * Title field in *Inner content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: inner_content.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * (Internal) Description field in *Inner content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Internal only, for self organisation
   * - **API ID Path**: inner_content.internal_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  internal_description: prismic.KeyTextField;

  /**
   * Connected to event field in *Inner content*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: inner_content.connected_to_event
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  connected_to_event: prismic.ContentRelationshipField<"event">;

  /**
   * Related to product field in *Inner content*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: inner_content.related_to_product
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  related_to_product: prismic.ContentRelationshipField<"product">;

  /**
   * Sorting weight field in *Inner content*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Useful in tabs
   * - **API ID Path**: inner_content.sorting_weight
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  sorting_weight: prismic.NumberField;

  /**
   * Slice Zone field in *Inner content*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: inner_content.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<InnerContentDocumentDataSlicesSlice>;
}

/**
 * Inner content document from Prismic
 *
 * - **API ID**: `inner_content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InnerContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InnerContentDocumentData>,
    "inner_content",
    Lang
  >;

/**
 * Item in *Menu navigation → Items*
 */
export interface MenuNavigationDocumentDataItemsItem {
  /**
   * Link field in *Menu navigation → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "CTA"
  >;
}

/**
 * Content for Menu navigation documents
 */
interface MenuNavigationDocumentData {
  /**
   * Items field in *Menu navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<MenuNavigationDocumentDataItemsItem>>;
}

/**
 * Menu navigation document from Prismic
 *
 * - **API ID**: `menu_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MenuNavigationDocumentData>,
    "menu_navigation",
    Lang
  >;

/**
 * Item in *Podcast → Tracklist*
 */
export interface PodcastDocumentDataTracklistItem {
  /**
   * Title field in *Podcast → Tracklist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Artist field in *Podcast → Tracklist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[].artist
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  artist: prismic.KeyTextField;

  /**
   * Link field in *Podcast → Tracklist*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Timestamp field in *Podcast → Tracklist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[].timestamp
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  timestamp: prismic.KeyTextField;
}

type PodcastDocumentDataSlicesSlice = never;

/**
 * Content for Podcast documents
 */
interface PodcastDocumentData {
  /**
   * Cover image field in *Podcast*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Episode name field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.episode_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  episode_name: prismic.KeyTextField;

  /**
   * Episode number field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Example 001
   * - **API ID Path**: podcast.episode_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  episode_number: prismic.KeyTextField;

  /**
   * Episode description field in *Podcast*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.episode_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  episode_description: prismic.RichTextField;

  /**
   * Artist field in *Podcast*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.artist
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  artist: ContentRelationshipFieldWithData<
    [
      {
        id: "artist";
        fields: [
          "name",
          "description",
          "image",
          "video",
          { id: "links"; fields: ["type", "link"] },
        ];
      },
    ]
  >;

  /**
   * Episode date field in *Podcast*
   *
   * - **Field Type**: Date
   * - **Placeholder**: The date of the episode
   * - **API ID Path**: podcast.episode_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  episode_date: prismic.DateField;

  /**
   * Track url field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Soundcloud track url
   * - **API ID Path**: podcast.track_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  track_url: prismic.KeyTextField;

  /**
   * Footnote field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.footnote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footnote: prismic.KeyTextField;

  /**
   * Tracklist field in *Podcast*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tracklist[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tracklist: prismic.GroupField<Simplify<PodcastDocumentDataTracklistItem>>;

  /**
   * Slice Zone field in *Podcast*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PodcastDocumentDataSlicesSlice> /**
   * Meta Title field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: podcast.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: podcast.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Podcast*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Podcast document from Prismic
 *
 * - **API ID**: `podcast`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PodcastDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PodcastDocumentData>,
    "podcast",
    Lang
  >;

/**
 * Item in *Product → Images*
 */
export interface ProductDocumentDataImagesItem {
  /**
   * image field in *Product → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Product → Related products*
 */
export interface ProductDocumentDataRelatedProductsItem {
  /**
   * Related product field in *Product → Related products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.related_products[].related_product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  related_product: ContentRelationshipFieldWithData<
    [
      {
        id: "product";
        fields: [
          "title",
          { id: "images"; fields: ["image"] },
          "price",
          "product_category",
          "product_type",
          "sorting_weight",
          "product_status",
          "description",
          "product_visibility",
        ];
      },
    ]
  >;

  /**
   * Call to action field in *Product → Related products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Example, "Goes great with", "To wear with your shirt"
   * - **API ID Path**: product.related_products[].call_to_action
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  call_to_action: prismic.KeyTextField;
}

type ProductDocumentDataSlicesSlice =
  | HeroSlice
  | TextColumnSlice
  | VinylPromoSectionSlice
  | NewsletterSubscriptionSlice
  | ContentSectionSlice
  | GridTileSlice
  | SpacerSlice
  | ImageGallerySlice
  | SoundCloudSlice;

/**
 * Item in *Product → Variants*
 */
export interface ProductDocumentDataVariantsItem {
  /**
   * Variant value field in *Product → Variants*
   *
   * - **Field Type**: Select
   * - **Placeholder**: What is the variants value
   * - **API ID Path**: product.variants[].variant_value
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant_value: prismic.SelectField<
    "XS" | "S" | "M" | "L" | "XL" | "XXL" | "Black" | "White"
  >;

  /**
   * Variant type field in *Product → Variants*
   *
   * - **Field Type**: Select
   * - **Placeholder**: What type of a variant is it
   * - **Default Value**: Size
   * - **API ID Path**: product.variants[].variant_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant_type: prismic.SelectField<"Size" | "Colour", "filled">;
}

/**
 * Item in *Product → Regional eligibility *
 */
export interface ProductDocumentDataRegionalEligibilityItem {
  /**
   * Region field in *Product → Regional eligibility *
   *
   * - **Field Type**: Select
   * - **Placeholder**: Region of availability, choose none if available everywhere
   * - **API ID Path**: product.regional_eligibility[].region
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  region: prismic.SelectField<
    | "Slovenia"
    | "EU"
    | "Non-EU Europe"
    | "UK"
    | "North America"
    | "Australia"
    | "Japan"
  >;
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of the product
   * - **API ID Path**: product.title
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Product category field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Which category best describes the product
   * - **Default Value**: Merch
   * - **API ID Path**: product.product_category
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  product_category: prismic.SelectField<
    | "Merch"
    | "Music"
    | "Albums"
    | "Donations"
    | "Tickets"
    | "Licenses"
    | "Currencies"
    | "Other",
    "filled"
  >;

  /**
   * Product type field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Is this a physical or digital item
   * - **Default Value**: Physical
   * - **API ID Path**: product.product_type
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  product_type: prismic.SelectField<"Physical" | "Digital", "filled">;

  /**
   * Images field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.images[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<ProductDocumentDataImagesItem>>;

  /**
   * Video field in *Product*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Video for product
   * - **API ID Path**: product.video
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Related products field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.related_products[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  related_products: prismic.GroupField<
    Simplify<ProductDocumentDataRelatedProductsItem>
  >;

  /**
   * Special notice field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional - Special notice or disclaimer goes here
   * - **API ID Path**: product.special_notice
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  special_notice: prismic.KeyTextField;

  /**
   * Checkout description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Item description visible in Stripe
   * - **API ID Path**: product.checkout_description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  checkout_description: prismic.KeyTextField /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descriptive text to highlight the features of the product
   * - **API ID Path**: product.description
   * - **Tab**: Rich content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */;
  description: prismic.RichTextField;

  /**
   * Display content slices field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Above description
   * - **API ID Path**: product.display_content_slices
   * - **Tab**: Rich content
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  display_content_slices: prismic.SelectField<
    "Above description" | "Below description",
    "filled"
  >;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Rich content
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Product status field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: What is the current product status
   * - **Default Value**: Available
   * - **API ID Path**: product.product_status
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/select
   */;
  product_status: prismic.SelectField<
    "Available" | "Preorder" | "Coming soon" | "Out of stock" | "Sold out",
    "filled"
  >;

  /**
   * Product visibility field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Is the product visible on site?
   * - **Default Value**: Visible
   * - **API ID Path**: product.product_visibility
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  product_visibility: prismic.SelectField<"Visible" | "Hidden", "filled">;

  /**
   * Price (EUR) field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Price of the product in EUR
   * - **API ID Path**: product.price
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Weight (g) field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Weight of the product in grams
   * - **API ID Path**: product.weight
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  weight: prismic.NumberField;

  /**
   * Featured product field in *Product*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product.featured_product
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured_product: prismic.BooleanField;

  /**
   * Sorting weight field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: The higher the number the higher on the list of products
   * - **API ID Path**: product.sorting_weight
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  sorting_weight: prismic.NumberField;

  /**
   * Related to event field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.related_to_event
   * - **Tab**: Attributes
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  related_to_event: ContentRelationshipFieldWithData<
    [
      {
        id: "event";
        fields: [
          "title",
          "venue_name",
          "date_start",
          "venue_address",
          "venue_logo",
        ];
      },
    ]
  > /**
   * Variants field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.variants[]
   * - **Tab**: Variants
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  variants: prismic.GroupField<Simplify<ProductDocumentDataVariantsItem>> /**
   * Regional eligibility  field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.regional_eligibility[]
   * - **Tab**: Limitations
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  regional_eligibility: prismic.GroupField<
    Simplify<ProductDocumentDataRegionalEligibilityItem>
  >;

  /**
   * Quantity limit field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Leave empty if no limit
   * - **API ID Path**: product.quantity_limit
   * - **Tab**: Limitations
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  quantity_limit: prismic.NumberField;

  /**
   * Cutoff date field in *Product*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: When does the product stop being eligible for sale, clear if sales always permitted
   * - **API ID Path**: product.cutoff_date
   * - **Tab**: Limitations
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  cutoff_date: prismic.TimestampField /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

type VenueDocumentDataSlicesSlice = never;

/**
 * Content for Venue documents
 */
interface VenueDocumentData {
  /**
   * Name field in *Venue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.name
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Venue*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Address field in *Venue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Full address, with street, zip, city
   * - **API ID Path**: venue.address
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Venue logo field in *Venue*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.venue_logo
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  venue_logo: prismic.ImageField<never>;

  /**
   * Map location url field in *Venue*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.map_location_url
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  map_location_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Coordinates field in *Venue*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.coordinates
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/geopoint
   */
  coordinates: prismic.GeoPointField;

  /**
   * Slice Zone field in *Venue*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.slices[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<VenueDocumentDataSlicesSlice> /**
   * Meta Title field in *Venue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: venue.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Venue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: venue.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Venue*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: venue.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Venue document from Prismic
 *
 * - **API ID**: `venue`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VenueDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<VenueDocumentData>, "venue", Lang>;

export type AllDocumentTypes =
  | ArtistDocument
  | ContentPageDocument
  | EventDocument
  | FooterContentDocument
  | HomePageDocument
  | InnerContentDocument
  | MenuNavigationDocument
  | PodcastDocument
  | ProductDocument
  | VenueDocument;

/**
 * Primary content in *Accordion → Default → Primary*
 */
export interface AccordionSliceDefaultPrimary {
  /**
   * Heading field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Allow Multiple Open field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accordion.default.primary.allowMultiple
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  allowMultiple: prismic.BooleanField;
}

/**
 * Primary content in *Accordion → Items*
 */
export interface AccordionSliceDefaultItem {
  /**
   * Title field in *Accordion → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *Accordion → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.items[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSliceDefaultPrimary>,
  Simplify<AccordionSliceDefaultItem>
>;

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault;

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Expandable accordion/FAQ sections
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSlice = prismic.SharedSlice<
  "accordion",
  AccordionSliceVariation
>;

/**
 * Default variation for ArtistList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArtistListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ArtistList*
 */
type ArtistListSliceVariation = ArtistListSliceDefault;

/**
 * ArtistList Shared Slice
 *
 * - **API ID**: `artist_list`
 * - **Description**: ArtistList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArtistListSlice = prismic.SharedSlice<
  "artist_list",
  ArtistListSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface ContentSectionSliceDefaultPrimary {
  /**
   * Content field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type ContentSectionSliceVariation = ContentSectionSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `content_section`
 * - **Description**: ContentSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSectionSlice = prismic.SharedSlice<
  "content_section",
  ContentSectionSliceVariation
>;

/**
 * Primary content in *EmbedBlock → Default → Primary*
 */
export interface EmbedBlockSliceDefaultPrimary {
  /**
   * Media field in *EmbedBlock → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: embed_block.default.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  media: prismic.EmbedField;

  /**
   * Heading field in *EmbedBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embed_block.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *EmbedBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embed_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for EmbedBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EmbedBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmbedBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EmbedBlock*
 */
type EmbedBlockSliceVariation = EmbedBlockSliceDefault;

/**
 * EmbedBlock Shared Slice
 *
 * - **API ID**: `embed_block`
 * - **Description**: EmbedBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EmbedBlockSlice = prismic.SharedSlice<
  "embed_block",
  EmbedBlockSliceVariation
>;

/**
 * Primary content in *EventList → Default → Primary*
 */
export interface EventListSliceDefaultPrimary {
  /**
   * Which events to show field in *EventList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: event_list.default.primary.show
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  show: prismic.SelectField<"All" | "Upcoming" | "Past">;

  /**
   * Title field in *EventList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for EventList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventList*
 */
type EventListSliceVariation = EventListSliceDefault;

/**
 * EventList Shared Slice
 *
 * - **API ID**: `event_list`
 * - **Description**: EventList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventListSlice = prismic.SharedSlice<
  "event_list",
  EventListSliceVariation
>;

/**
 * Item in *TileGrid → Default → Primary → Tiles*
 */
export interface GridTileSliceDefaultPrimaryTilesItem {
  /**
   * Size * field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: What is the size of the tile
   * - **API ID Path**: grid_tile.default.primary.tiles[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"Square" | "Portrait">;

  /**
   * Headline field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (optional)
   * - **API ID Path**: grid_tile.default.primary.tiles[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Content field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (optional)
   * - **API ID Path**: grid_tile.default.primary.tiles[].content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  content: prismic.KeyTextField;

  /**
   * Image field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_tile.default.primary.tiles[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_tile.default.primary.tiles[].video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Link field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Link
   * - **Placeholder**: (optional)
   * - **API ID Path**: grid_tile.default.primary.tiles[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Background colour field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Color
   * - **Placeholder**: (optional)
   * - **API ID Path**: grid_tile.default.primary.tiles[].background_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;

  /**
   * Text colour field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Color
   * - **Placeholder**: (optional)
   * - **API ID Path**: grid_tile.default.primary.tiles[].text_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  text_colour: prismic.ColorField;

  /**
   * Override class definition field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (Optiona) - if you know what you're doing, tailwind
   * - **API ID Path**: grid_tile.default.primary.tiles[].override_class_definition
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  override_class_definition: prismic.KeyTextField;
}

/**
 * Primary content in *TileGrid → Default → Primary*
 */
export interface GridTileSliceDefaultPrimary {
  /**
   * Tiles field in *TileGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_tile.default.primary.tiles[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tiles: prismic.GroupField<Simplify<GridTileSliceDefaultPrimaryTilesItem>>;
}

/**
 * Default variation for TileGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridTileSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridTileSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TileGrid*
 */
type GridTileSliceVariation = GridTileSliceDefault;

/**
 * TileGrid Shared Slice
 *
 * - **API ID**: `grid_tile`
 * - **Description**: GridTile
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridTileSlice = prismic.SharedSlice<
  "grid_tile",
  GridTileSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary CTA Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.primaryCtaText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primaryCtaText: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.primaryCtaLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primaryCtaLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondaryCtaText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondaryCtaText: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondaryCtaLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondaryCtaLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * Text Alignment field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: hero.default.primary.textAlignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  textAlignment: prismic.SelectField<"left" | "center", "filled">;

  /**
   * Overlay Opacity (0-100) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.overlayOpacity
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  overlayOpacity: prismic.NumberField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with heading, description, CTAs and background image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageGallery → Default → Primary*
 */
export interface ImageGallerySliceDefaultPrimary {
  /**
   * Heading field in *ImageGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Layout field in *ImageGallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: grid
   * - **API ID Path**: image_gallery.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  layout: prismic.SelectField<"grid" | "masonry", "filled">;

  /**
   * Columns field in *ImageGallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 3
   * - **API ID Path**: image_gallery.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"2" | "3" | "4", "filled">;
}

/**
 * Primary content in *ImageGallery → Items*
 */
export interface ImageGallerySliceDefaultItem {
  /**
   * Image field in *ImageGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *ImageGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageGallerySliceDefaultPrimary>,
  Simplify<ImageGallerySliceDefaultItem>
>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: Image gallery with grid or masonry layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGallerySlice = prismic.SharedSlice<
  "image_gallery",
  ImageGallerySliceVariation
>;

/**
 * Primary content in *Newsletter → Default → Primary*
 */
export interface NewsletterSubscriptionSliceDefaultPrimary {
  /**
   * List type field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: General
   * - **API ID Path**: newsletter_subscription.default.primary.list_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  list_type: prismic.SelectField<"General" | "Festival", "filled">;

  /**
   * Override title field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (Optional) Replace title in widget
   * - **API ID Path**: newsletter_subscription.default.primary.override_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  override_title: prismic.KeyTextField;

  /**
   * Override description field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: (Optional) Replace dsecription in widget
   * - **API ID Path**: newsletter_subscription.default.primary.override_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  override_description: prismic.KeyTextField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSubscriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSubscriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSubscriptionSliceVariation = NewsletterSubscriptionSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter_subscription`
 * - **Description**: NewsletterSubscription
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSubscriptionSlice = prismic.SharedSlice<
  "newsletter_subscription",
  NewsletterSubscriptionSliceVariation
>;

/**
 * Primary content in *PodcastList → Default → Primary*
 */
export interface PodcastListSliceDefaultPrimary {
  /**
   * Title field in *PodcastList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *PodcastList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Render frame field in *PodcastList → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: podcast_list.default.primary.render_frame
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;
}

/**
 * Default variation for PodcastList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PodcastListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PodcastListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PodcastList*
 */
type PodcastListSliceVariation = PodcastListSliceDefault;

/**
 * PodcastList Shared Slice
 *
 * - **API ID**: `podcast_list`
 * - **Description**: PodcastList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PodcastListSlice = prismic.SharedSlice<
  "podcast_list",
  PodcastListSliceVariation
>;

/**
 * Primary content in *EventIntro → Default → Primary*
 */
export interface PoemSliceDefaultPrimary {
  /**
   * Content field in *EventIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: poem.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for EventIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PoemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PoemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventIntro*
 */
type PoemSliceVariation = PoemSliceDefault;

/**
 * EventIntro Shared Slice
 *
 * - **API ID**: `poem`
 * - **Description**: Poem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PoemSlice = prismic.SharedSlice<"poem", PoemSliceVariation>;

/**
 * Item in *ProductList → Manual selection → Primary → Products*
 */
export interface ProductListSliceManualPrimaryProductsItem {
  /**
   * Product field in *ProductList → Manual selection → Primary → Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.manual.primary.products[].product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product: ContentRelationshipFieldWithData<
    [{ id: "product"; fields: ["title"] }]
  >;
}

/**
 * Primary content in *ProductList → Category → Primary*
 */
export interface ProductListSliceDefaultPrimary {
  /**
   * Title field in *ProductList → Category → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title of the section
   * - **API ID Path**: product_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Category field in *ProductList → Category → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.default.primary.category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "Merch"
    | "Music"
    | "Albums"
    | "Donations"
    | "Tickets"
    | "Licenses"
    | "Currencies"
    | "Other"
  >;

  /**
   * Description field in *ProductList → Category → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of the section
   * - **API ID Path**: product_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Render frame field in *ProductList → Category → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_list.default.primary.render_frame
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;
}

/**
 * Category variation for ProductList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductListSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProductList → Featured → Primary*
 */
export interface ProductListSliceFeaturedPrimary {
  /**
   * Title field in *ProductList → Featured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.featured.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProductList → Featured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.featured.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Render frame field in *ProductList → Featured → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_list.featured.primary.render_frame
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;
}

/**
 * Featured variation for ProductList Slice
 *
 * - **API ID**: `featured`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductListSliceFeatured = prismic.SharedSliceVariation<
  "featured",
  Simplify<ProductListSliceFeaturedPrimary>,
  never
>;

/**
 * Primary content in *ProductList → Manual selection → Primary*
 */
export interface ProductListSliceManualPrimary {
  /**
   * Title field in *ProductList → Manual selection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.manual.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProductList → Manual selection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.manual.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Products field in *ProductList → Manual selection → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_list.manual.primary.products[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  products: prismic.GroupField<
    Simplify<ProductListSliceManualPrimaryProductsItem>
  >;

  /**
   * Render frame field in *ProductList → Manual selection → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_list.manual.primary.render_frame
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  render_frame: prismic.BooleanField;
}

/**
 * Manual selection variation for ProductList Slice
 *
 * - **API ID**: `manual`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductListSliceManual = prismic.SharedSliceVariation<
  "manual",
  Simplify<ProductListSliceManualPrimary>,
  never
>;

/**
 * Slice variation for *ProductList*
 */
type ProductListSliceVariation =
  | ProductListSliceDefault
  | ProductListSliceFeatured
  | ProductListSliceManual;

/**
 * ProductList Shared Slice
 *
 * - **API ID**: `product_list`
 * - **Description**: ProductList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductListSlice = prismic.SharedSlice<
  "product_list",
  ProductListSliceVariation
>;

/**
 * Primary content in *SoundCloud → Default → Primary*
 */
export interface SoundCloudSliceDefaultPrimary {
  /**
   * Soundcloud url field in *SoundCloud → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_cloud.default.primary.url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  url: prismic.KeyTextField;

  /**
   * Height field in *SoundCloud → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_cloud.default.primary.height
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  height: prismic.NumberField;

  /**
   * Color field in *SoundCloud → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_cloud.default.primary.color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color: prismic.ColorField;
}

/**
 * Default variation for SoundCloud Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SoundCloudSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SoundCloudSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SoundCloud*
 */
type SoundCloudSliceVariation = SoundCloudSliceDefault;

/**
 * SoundCloud Shared Slice
 *
 * - **API ID**: `sound_cloud`
 * - **Description**: SoundCloud
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SoundCloudSlice = prismic.SharedSlice<
  "sound_cloud",
  SoundCloudSliceVariation
>;

/**
 * Primary content in *Spacer → Default → Primary*
 */
export interface SpacerSliceDefaultPrimary {
  /**
   * Size field in *Spacer → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: medium
   * - **API ID Path**: spacer.default.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"small" | "medium" | "large" | "xlarge", "filled">;

  /**
   * Mobile Size field in *Spacer → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: small
   * - **API ID Path**: spacer.default.primary.mobileSize
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  mobileSize: prismic.SelectField<
    "small" | "medium" | "large" | "xlarge",
    "filled"
  >;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpacerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type SpacerSliceVariation = SpacerSliceDefault;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: Configurable vertical spacing between sections
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSlice = prismic.SharedSlice<"spacer", SpacerSliceVariation>;

/**
 * Primary content in *Tabs → Default → Primary*
 */
export interface TabsSliceDefaultPrimary {
  /**
   * Heading field in *Tabs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabs.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *Tabs → Items*
 */
export interface TabsSliceDefaultItem {
  /**
   * Tab Label field in *Tabs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabs.items[].tabLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tabLabel: prismic.KeyTextField;

  /**
   * Tab ID (for URL hash) field in *Tabs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabs.items[].tabId
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tabId: prismic.KeyTextField;

  /**
   * Content field in *Tabs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabs.items[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Tabs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TabsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TabsSliceDefaultPrimary>,
  Simplify<TabsSliceDefaultItem>
>;

/**
 * Slice variation for *Tabs*
 */
type TabsSliceVariation = TabsSliceDefault;

/**
 * Tabs Shared Slice
 *
 * - **API ID**: `tabs`
 * - **Description**: Horizontal tabs for organizing content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TabsSlice = prismic.SharedSlice<"tabs", TabsSliceVariation>;

/**
 * Item in *TextColumns → Column - Text → Primary → Columns*
 */
export interface TextColumnSliceDefaultPrimaryColumnsItem {
  /**
   * Heading field in *TextColumns → Column - Text → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.columns[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *TextColumns → Column - Text → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.columns[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Item in *TextColumns → Column - With Image → Primary → Columns*
 */
export interface TextColumnSliceColumnWithImagePrimaryColumnsItem {
  /**
   * Image field in *TextColumns → Column - With Image → Primary → Columns*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.columns[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *TextColumns → Column - With Image → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.columns[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *TextColumns → Column - With Image → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.columns[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *TextColumns → Column - Text → Primary*
 */
export interface TextColumnSliceDefaultPrimary {
  /**
   * Heading field in *TextColumns → Column - Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *TextColumns → Column - Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Columns field in *TextColumns → Column - Text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.default.primary.columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  columns: prismic.GroupField<
    Simplify<TextColumnSliceDefaultPrimaryColumnsItem>
  >;
}

/**
 * Column - Text variation for TextColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextColumnSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextColumns → Column - With Image → Primary*
 */
export interface TextColumnSliceColumnWithImagePrimary {
  /**
   * Heading field in *TextColumns → Column - With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *TextColumns → Column - With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Columns field in *TextColumns → Column - With Image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_column.columnWithImage.primary.columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  columns: prismic.GroupField<
    Simplify<TextColumnSliceColumnWithImagePrimaryColumnsItem>
  >;
}

/**
 * Column - With Image variation for TextColumns Slice
 *
 * - **API ID**: `columnWithImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnSliceColumnWithImage = prismic.SharedSliceVariation<
  "columnWithImage",
  Simplify<TextColumnSliceColumnWithImagePrimary>,
  never
>;

/**
 * Slice variation for *TextColumns*
 */
type TextColumnSliceVariation =
  | TextColumnSliceDefault
  | TextColumnSliceColumnWithImage;

/**
 * TextColumns Shared Slice
 *
 * - **API ID**: `text_column`
 * - **Description**: TextColumn
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnSlice = prismic.SharedSlice<
  "text_column",
  TextColumnSliceVariation
>;

/**
 * Primary content in *VinylPromoSection → Default → Primary*
 */
export interface VinylPromoSectionSliceDefaultPrimary {
  /**
   * Headline field in *VinylPromoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vinyl_promo_section.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Description field in *VinylPromoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vinyl_promo_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Product field in *VinylPromoSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: vinyl_promo_section.default.primary.product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product: ContentRelationshipFieldWithData<
    [{ id: "product"; fields: ["title"] }]
  >;

  /**
   * Display add to cart field in *VinylPromoSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: vinyl_promo_section.default.primary.display_add_to_cart
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  display_add_to_cart: prismic.BooleanField;
}

/**
 * Default variation for VinylPromoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VinylPromoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VinylPromoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VinylPromoSection*
 */
type VinylPromoSectionSliceVariation = VinylPromoSectionSliceDefault;

/**
 * VinylPromoSection Shared Slice
 *
 * - **API ID**: `vinyl_promo_section`
 * - **Description**: VinylPromoSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VinylPromoSectionSlice = prismic.SharedSlice<
  "vinyl_promo_section",
  VinylPromoSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArtistDocument,
      ArtistDocumentData,
      ArtistDocumentDataLinksItem,
      ArtistDocumentDataSlicesSlice,
      ContentPageDocument,
      ContentPageDocumentData,
      ContentPageDocumentDataSlicesSlice,
      EventDocument,
      EventDocumentData,
      EventDocumentDataArtistsItem,
      EventDocumentDataSlicesSlice,
      FooterContentDocument,
      FooterContentDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      InnerContentDocument,
      InnerContentDocumentData,
      InnerContentDocumentDataSlicesSlice,
      MenuNavigationDocument,
      MenuNavigationDocumentData,
      MenuNavigationDocumentDataItemsItem,
      PodcastDocument,
      PodcastDocumentData,
      PodcastDocumentDataTracklistItem,
      PodcastDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataImagesItem,
      ProductDocumentDataRelatedProductsItem,
      ProductDocumentDataSlicesSlice,
      ProductDocumentDataVariantsItem,
      ProductDocumentDataRegionalEligibilityItem,
      VenueDocument,
      VenueDocumentData,
      VenueDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionSlice,
      AccordionSliceDefaultPrimary,
      AccordionSliceDefaultItem,
      AccordionSliceVariation,
      AccordionSliceDefault,
      ArtistListSlice,
      ArtistListSliceVariation,
      ArtistListSliceDefault,
      ContentSectionSlice,
      ContentSectionSliceDefaultPrimary,
      ContentSectionSliceVariation,
      ContentSectionSliceDefault,
      EmbedBlockSlice,
      EmbedBlockSliceDefaultPrimary,
      EmbedBlockSliceVariation,
      EmbedBlockSliceDefault,
      EventListSlice,
      EventListSliceDefaultPrimary,
      EventListSliceVariation,
      EventListSliceDefault,
      GridTileSlice,
      GridTileSliceDefaultPrimaryTilesItem,
      GridTileSliceDefaultPrimary,
      GridTileSliceVariation,
      GridTileSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageGallerySlice,
      ImageGallerySliceDefaultPrimary,
      ImageGallerySliceDefaultItem,
      ImageGallerySliceVariation,
      ImageGallerySliceDefault,
      NewsletterSubscriptionSlice,
      NewsletterSubscriptionSliceDefaultPrimary,
      NewsletterSubscriptionSliceVariation,
      NewsletterSubscriptionSliceDefault,
      PodcastListSlice,
      PodcastListSliceDefaultPrimary,
      PodcastListSliceVariation,
      PodcastListSliceDefault,
      PoemSlice,
      PoemSliceDefaultPrimary,
      PoemSliceVariation,
      PoemSliceDefault,
      ProductListSlice,
      ProductListSliceDefaultPrimary,
      ProductListSliceFeaturedPrimary,
      ProductListSliceManualPrimaryProductsItem,
      ProductListSliceManualPrimary,
      ProductListSliceVariation,
      ProductListSliceDefault,
      ProductListSliceFeatured,
      ProductListSliceManual,
      SoundCloudSlice,
      SoundCloudSliceDefaultPrimary,
      SoundCloudSliceVariation,
      SoundCloudSliceDefault,
      SpacerSlice,
      SpacerSliceDefaultPrimary,
      SpacerSliceVariation,
      SpacerSliceDefault,
      TabsSlice,
      TabsSliceDefaultPrimary,
      TabsSliceDefaultItem,
      TabsSliceVariation,
      TabsSliceDefault,
      TextColumnSlice,
      TextColumnSliceDefaultPrimaryColumnsItem,
      TextColumnSliceDefaultPrimary,
      TextColumnSliceColumnWithImagePrimaryColumnsItem,
      TextColumnSliceColumnWithImagePrimary,
      TextColumnSliceVariation,
      TextColumnSliceDefault,
      TextColumnSliceColumnWithImage,
      VinylPromoSectionSlice,
      VinylPromoSectionSliceDefaultPrimary,
      VinylPromoSectionSliceVariation,
      VinylPromoSectionSliceDefault,
    };
  }
}
