import { Country, CountryCode } from "@/domain/checkout/types/country";

export const countries: Record<CountryCode, Country> = {
  SI: {
    code: "SI",
    name: "Slovenia",
    flag: "🇸🇮",
    callingCode: "+386",
    region: "Slovenia",
    orderPriority: 100,
  },
  AT: {
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    callingCode: "+43",
    region: "EU",
  },
  BE: {
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    callingCode: "+32",
    region: "EU",
  },
  BG: {
    code: "BG",
    name: "Bulgaria",
    flag: "🇧🇬",
    callingCode: "+359",
    region: "EU",
  },
  HR: {
    code: "HR",
    name: "Croatia",
    flag: "🇭🇷",
    callingCode: "+385",
    region: "EU",
  },
  CY: {
    code: "CY",
    name: "Cyprus",
    flag: "🇨🇾",
    callingCode: "+357",
    region: "EU",
  },
  CZ: {
    code: "CZ",
    name: "Czech Republic",
    flag: "🇨🇿",
    callingCode: "+420",
    region: "EU",
  },
  DK: {
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    callingCode: "+45",
    region: "EU",
  },
  EE: {
    code: "EE",
    name: "Estonia",
    flag: "🇪🇪",
    callingCode: "+372",
    region: "EU",
  },
  FI: {
    code: "FI",
    name: "Finland",
    flag: "🇫🇮",
    callingCode: "+358",
    region: "EU",
  },
  FR: {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    callingCode: "+33",
    region: "EU",
  },
  DE: {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    callingCode: "+49",
    region: "EU",
  },
  GR: {
    code: "GR",
    name: "Greece",
    flag: "🇬🇷",
    callingCode: "+30",
    region: "EU",
  },
  HU: {
    code: "HU",
    name: "Hungary",
    flag: "🇭🇺",
    callingCode: "+36",
    region: "EU",
  },
  IE: {
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    callingCode: "+353",
    region: "EU",
  },
  IT: {
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    callingCode: "+39",
    region: "EU",
  },
  LV: {
    code: "LV",
    name: "Latvia",
    flag: "🇱🇻",
    callingCode: "+371",
    region: "EU",
  },
  LT: {
    code: "LT",
    name: "Lithuania",
    flag: "🇱🇹",
    callingCode: "+370",
    region: "EU",
  },
  LU: {
    code: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
    callingCode: "+352",
    region: "EU",
  },
  MT: {
    code: "MT",
    name: "Malta",
    flag: "🇲🇹",
    callingCode: "+356",
    region: "EU",
  },
  NL: {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    callingCode: "+31",
    region: "EU",
  },
  PL: {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    callingCode: "+48",
    region: "EU",
  },
  PT: {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    callingCode: "+351",
    region: "EU",
  },
  RO: {
    code: "RO",
    name: "Romania",
    flag: "🇷🇴",
    callingCode: "+40",
    region: "EU",
  },
  SK: {
    code: "SK",
    name: "Slovakia",
    flag: "🇸🇰",
    callingCode: "+421",
    region: "EU",
  },
  ES: {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    callingCode: "+34",
    region: "EU",
  },
  SE: {
    code: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    callingCode: "+46",
    region: "EU",
  },
  UK: {
    code: "UK",
    name: "United Kingdom",
    flag: "🇬🇧",
    callingCode: "+44",
    region: "UK",
  },
  RS: {
    code: "RS",
    name: "Serbia",
    flag: "🇷🇸",
    callingCode: "+381",
    region: "Non-EU Europe",
  },
  BA: {
    code: "BA",
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    callingCode: "+387",
    region: "Non-EU Europe",
  },
  ME: {
    code: "ME",
    name: "Montenegro",
    flag: "🇲🇪",
    callingCode: "+382",
    region: "Non-EU Europe",
  },
  MK: {
    code: "MK",
    name: "North Macedonia",
    flag: "🇲🇰",
    callingCode: "+389",
    region: "Non-EU Europe",
  },
  US: {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    callingCode: "+1",
    region: "North America",
  },
  CA: {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    callingCode: "+1",
    region: "North America",
  },
  AU: {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    callingCode: "+61",
    region: "Australia",
  },
  JP: {
    code: "JP",
    name: "Japan",
    flag: "🇯🇵",
    callingCode: "+81",
    region: "Australia",
  },
};
