import {
  EMAIL_OCTOPUS_API_KEY,
  EMAIL_OCTOPUS_FESTIVAL_LIST_ID,
  EMAIL_OCTOPUS_GENERAL_LIST_ID,
  EMAIL_OCTOPUS_TICKET_BUYERS_LIST_ID,
} from "@/lib/services/env/private";

export const EMAIL_NEWSLETTER_API_KEY = EMAIL_OCTOPUS_API_KEY;
export const EMAIL_NEWSLETTER_GENERAL_LIST_ID = EMAIL_OCTOPUS_GENERAL_LIST_ID;
export const EMAIL_NEWSLETTER_FESTIVAL_LIST_ID = EMAIL_OCTOPUS_FESTIVAL_LIST_ID;
export const EMAIL_NEWSLETTER_TICKET_BUYERS_LIST_ID =
  EMAIL_OCTOPUS_TICKET_BUYERS_LIST_ID;
