// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  artist_list: dynamic(() => import("./ArtistList")),
  content_section: dynamic(() => import("./TextBlock")),
  embed_block: dynamic(() => import("./EmbedBlock")),
  event_list: dynamic(() => import("./EventList")),
  grid_tile: dynamic(() => import("./TileGrid")),
  hero: dynamic(() => import("./Hero")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  newsletter_subscription: dynamic(() => import("./Newsletter")),
  podcast_list: dynamic(() => import("./PodcastList")),
  poem: dynamic(() => import("./EventIntro")),
  product_list: dynamic(() => import("./ProductList")),
  save_the_date: dynamic(() => import("./SaveTheDate")),
  snowfall: dynamic(() => import("./Snowfall")),
  sound_cloud: dynamic(() => import("./SoundCloud")),
  spacer: dynamic(() => import("./Spacer")),
  tabs: dynamic(() => import("./Tabs")),
  text_column: dynamic(() => import("./TextColumns")),
  venue_list: dynamic(() => import("./VenueList")),
  vinyl_promo_section: dynamic(() => import("./VinylPromoSection")),
};
