// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_section: dynamic(() => import("./TextBlock")),
  embed_block: dynamic(() => import("./EmbedBlock")),
  grid_tile: dynamic(() => import("./TileGrid")),
  hero: dynamic(() => import("./Hero")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  newsletter_subscription: dynamic(() => import("./Newsletter")),
  podcast_list: dynamic(() => import("./PodcastList")),
  product_list: dynamic(() => import("./ProductList")),
  text_column: dynamic(() => import("./TextColumns")),
};
