// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_section: dynamic(() => import("./TextBlock")),
  embed_block: dynamic(() => import("./EmbedBlock")),
  grid_tile: dynamic(() => import("./GridTile")),
  newsletter_subscription: dynamic(() => import("./Newsletter")),
  product_list: dynamic(() => import("./ProductList")),
  text_column: dynamic(() => import("./TextColumns")),
  text_image_block: dynamic(() => import("./TextImageBlock")),
};
